import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import '@radix-ui/themes/styles.css';
import { Theme, ThemePanel } from "@radix-ui/themes";
import './theme-config.css'


const inter = Inter({ subsets: ["latin"], variable: '--font-inter', });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
      <Theme accentColor="iris">
        

        <Navbar />
        <main className="p-5 min-h-screen">
        {children}

        </main>
        {/* <ThemePanel /> */}
       
        
        </Theme>

        
        </body>
    </html>
  );
}
